var arrLang = {
    'en':{
        'subtitle':'Integrating nature-based water Reuse strategies with advanced Monitoring of the Presence and impact of MicroPollutants and MicroPlastics.',
        'project':'Project',
        'overview':'Overview',
        'packages':'Work Packages',
        'field':'Field sites',
        'mesocosm':'Mesocosm studies',
        'members':'Members',
        'publis&news':"Publications & News",
        'news':'News',
        'conferences':'Conferences',
        'publications':'Publications',
        'jobOffers':'Job Offers',
        'supporters':'Supporters',
        'relatedProjects':'Related projects',
        'advisoryBoard':'Advisory board',
        'authorities':'Authorities & utilities',
        'universities':'Universities',
        'techCompanies':'Tech. companies',
        'menu':'MENU',
        'h3ProjectOverview':'PROJECT OVERVIEW',
        'generalInfo':'General Information',
        'fundingAgency':'FUNDING AGENCY',
        'duration':'DURATION',
        'coordinator':'COORDINATOR',
        'leadResearchers':'LEAD RESEARCHERS',
        'otherResearchers':'OTHER RESEARCHERS',
        'budget':'BUDGET',
        'fundingInfo':'Spanish State Research Agency (AEI), Code: PID2020-115456RB-I00',
        'linkInfoProjecte':'Project information',
        'h3WorkPackages':'WORK PACKAGES',
        'h3FieldSites':'FIELD SITES',
        'h3Mesocosm':'MESOCOSM STUDIES',
        'h3Members':'MEMBERS',
        'h3News':'NEWS',
        'h3RelatedProjects':'RELATED PROJECTS',
        'h3Advisory':'ADVISORY BOARD',
        'h3Authorities':'AUTHORITIES & UTILITIES',
        'h3Universities':'UNIVERSITIES',
        'h3techCompanies':'TECH. COMPANIES & OTHERS',
        'h3Conferences':'CONFERENCES',
        'h3Publications':'PUBLICATIONS',
        'h3JobOffers':'JOB OFFERS',
        'about':'About',
        'quickLinks':'Quick Links',
        'text1span1':'The aim of the ReUseMP3 project is to explore the feasibility of using ',
        'text1span2':'(NBS) with direct reuse purposes- including',
        'text1span3':'of crops for food production in cities in a more sustainable way.',
        'text1span4':'A range of',
        'text1span5':' including target analysis of known',
        'text1span6':'but also a wide-scope suspect and non-target analysis are applied to provide a better overview of the presence and removal of substances of emerging concern along the water reuse cycle as well as their',
        'text1span7':'and their additives are also monitored in these studies, which include',
        'text1span8':'under controlled conditions with real grey/wastewater, as well as',
        'text1span9':'All the data collected during the project will also allow the development of innovative',
        'text1b1':'nature-based solutions ',
        'text1b2':' irrigation',
        'text1b3':'analytical methodologies',
        'text1b4':'emerging pollutants',
        'text1b5':'impact to the environment and human health',
        'text1b6':'Microplastics',
        'text1b7':'lab-scale experiments',
        'text1b8':'field studies',
        'text1b9':'decision support tools for water management',
        "wp1":"Hydroponic greywater treatment and reuse system for crops production under controlled conditions",
        "wp2":"Field case studies of reclaimed water irrigation for crops production and/or NBS applications",
        "wp3":"Advanced analytical tools to monitor water treatment technologies and irrigation systems",
        "wp4":"Environmental Risk Assessment (ERA)",
        "wp5":"Human Risk Assessment derived from crop production",
        "wp6":"ReuseMP3 decision support tool",
        "field1":" Municipal gardens irrigated with treated urban wastewater (tertiary treatment)",
        "field2":" Vineyards irrigated with treated urban wastewater (tertiary treatment)",
        "field3":" Ornamental an edible-plants irrigated with NBS based treated greywater (hydroponic wetland)",
        "field4":" Urban garden irrigated with NBS based treated greywater (wetwall)",
        "field5":" Herbs irrigated with NBS based treated urban wastewater (UASB-wetland)",
        "lesbos":"Lesbos (Greece):",
        "mesocosmText":"The hydroponic pilot plant was built in the ICRA PLANTEA platform to test edible plant synthetic and/or real greywater treatment and crop production. It is made up of several lines that can work in parallel, with distinct influent water, and sensors for temperature, humidity, and light intensity. The canals can be filled in with light expanded clay aggregates (LECA) as inert substratum and can host up to 8 plants per canal. The presence of air bubbling inside the canals is obtained by introducing air dissipators in the water phase, if needed.",
        "aboutText":"The aim of the ReUseMP3 project is to explore the feasibility of using nature-based solutions (NBS) with direct reuse purposes- including irrigation of crops for food production in cities in a more sustainable way. A range of analytical methodologies including target analysis of known emerging pollutants but also a wide-scope suspect and non-target analysis are applied to provide a better overview of the presence and removal of substances of emerging concern along the water reuse cycle as well as their impact to the environment and human health.",
        "footerFundingText":"The project is funded by AEI with the code PID2020-115456RB-I00 /MCIN/AEI /10.13039/501100011033.",
        "moreInfo":"More information",
        "publiLink":"PUBLICATION LINK",
    },
    'es':{
        'subtitle':'Integración de estrategias de reutilización del agua inspiradas en la naturaleza con la presencia e impacto de microcontaminantes y microplásticos mediante análisis avanzado.',
        'project':'Proyecto',
        'overview':'Descripción general',
        'packages':'Paquetes de trabajo',
        'field':'Sitios de campo',
        'mesocosm':'Estudios mesocosm',
        'members':'Miembros',
        'publis&news':"Publicaciones y Noticias",
        'news':'Noticias',
        'conferences':'Conferencias',
        'publications':'Publicaciones',
        'jobOffers':'Ofertas de trabajo',
        'supporters':'Partidarios',
        'relatedProjects':'Proyectos relacionados',
        'advisoryBoard':'Junta asesora',
        'authorities':'Autoridades y utilidades',
        'universities':'Universidades',
        'techCompanies':'Empresas tecnológicas',
        'menu':'MENÚ',
        'h3ProjectOverview':'DESCRIPCIÓN GENERAL',
        'generalInfo':'Información General',
        'fundingAgency':'AGENCIA DE FINANCIAMIENTO',
        'duration':'DURACIÓN',
        'coordinator':'COORDINADOR',
        'leadResearchers':'INVESTIGADORES PRINCIPALES',
        'otherResearchers':'OTROS INVESTIGADORES',
        'budget':'PRESUPUESTO',
        'fundingInfo':'Agencia estatal de investigación Española (AEI), Codigo: PID2020-115456RB-I00',
        'linkInfoProjecte':'Información del proyecto',
        'h3WorkPackages':'PAQUETES DE TRABAJO',
        'h3FieldSites':'SITIOS DE CAMPO',
        'h3Mesocosm':'ESTUDIOS MESOCOSM',
        'h3Members':'MIEMBROS',
        'h3News':'NOTICIAS',
        'h3RelatedProjects':'PROYECTOS RELACIONADOS',
        'h3Advisory':'JUNTA ASESORA',
        'h3Authorities':'AUTORIDADES Y UTILIDADES',
        'h3Universities':'UNIVERSIDADES',
        'h3techCompanies':'EMPRESAS TECNOLÓGICAS Y OTROS',
        'h3Conferences':'CONFERENCIAS',
        'h3Publications':'PUBLICACIONES',
        'h3JobOffers':'OFERTAS DE TRABAJO',
        'about':'Acerca de',
        'quickLinks':'Enlaces rápidos',
        'text1span1':'El objetivo del proyecto ReUseMP3 es explorar la viabilidad del uso de ',
        'text1span2':'(NBS) con fines de reutilización directa, incluido el',
        'text1span3':'en las ciudades para la producción de alimentos de una manera más sostenible.',
        'text1span4':'Se aplica una',
        'text1span5':' incluido el análisis target de',
        'text1span6':'conocidos, pero también un wide-scope suspect y non-target para proporcionar una mejor visión general de la presencia y eliminación de sustancias de preocupación emergente a lo largo del ciclo de reutilización del agua, así como su',
        'text1span7':'y sus aditivos también se controlan en estos estudios, que incluyen',
        'text1span8':'en condiciones controladas con aguas residuales/grises reales, así como',
        'text1span9':'Todos los datos recopilados durante el proyecto también permitirán el desarrollo de',
        'text1b1':'soluciones basadas en la naturaleza ',
        'text1b2':' riego de cultivos',
        'text1b3':'variedad de metodologías analíticas,',
        'text1b4':'contaminantes emergentes',
        'text1b5':'impacto en el medio ambiente y la salud humana',
        'text1b6':'Los microplásticos',
        'text1b7':'experimentos a escala de laboratorio',
        'text1b8':'estudios de campo',
        'text1b9':'herramientas innovadoras de apoyo a la toma de decisiones para la gestión del agua',
        "wp1":"Sistemas hidropónicos de tratamiento y reutilización de aguas grises para la producción de cultivos en condiciones controladas",
        "wp2":"Estudios de campo de riego con agua regenerada para la producción de cultivos y/o aplicaciones de NBS",
        "wp3":"Herramientas analíticas avanzadas para monitorear tecnologías de tratamiento de agua y sistemas de riego",
        "wp4":"Evaluación del riesgo ambiental (ERA)",
        "wp5":"Evaluación del riesgo humano derivado de la producción de cultivos",
        "wp6":"Herramienta ReUseMP3 de apoyo a la toma de decisiones",
        "field1":" Jardines municipales regados con aguas residuales urbanas tratadas (tratamiento terciario)",
        "field2":" Viñedos regados con aguas residuales urbanas tratadas (tratamiento terciario)",
        "field3":" Plantas ornamentales y comestibles regadas con aguas grises tratadas con NBS (humedal hidropónico)",
        "field4":" Huerto urbano regado con aguas grises tratadas con NBS (pared vertical)",
        "field5":" Hierbas regadas con aguas residuales urbanas tratadas con NBS (UASB-humedal construido)",
        "lesbos":"Lesbos (Grecia):",
        "mesocosmText":"La planta piloto hidropónica se construyó en la plataforma ICRA PLANTEA para probar el tratamiento de aguas grises sintéticas y/o reales y la producción de cultivos de plantas comestibles. El sistema está compuesto por varias líneas que pueden trabajar en paralelo, con distintas entradas de agua, y sensores de temperatura, humedad e intensidad lumínica. Los canales se pueden rellenar con arcilla expandida (LECA) como sustrato inerte y pueden albergar hasta 8 plantas por canal. La presencia de aire en el interior de los canales se obtiene introduciendo disipadores de aire en el agua, si es necesario.",
        "aboutText":"El objetivo del proyecto ReUseMP3 es explorar la viabilidad del uso de soluciones basadas en la naturaleza (NBS) con fines de reutilización directa, incluido el riego de cultivos en las ciudades para la producción de alimentos de una manera más sostenible. Se aplica una variedad de metodologías analíticas, incluido el análisis target de contaminantes emergentes conocidos, pero también un wide-scope suspect y non-target para proporcionar una mejor visión general de la presencia y eliminación de sustancias de preocupación emergente a lo largo del ciclo de reutilización del agua, así como su impacto en el medio ambiente y la salud humana.",
        "footerFundingText":"Proyecto financiado por AEI con el código PID2020-115456RB-I00 /MCIN/AEI /10.13039/501100011033.",
        "moreInfo":"Más información",
        "publiLink":"LINK DE LA PUBLICACIÓN",
    },
    'cat':{
        'subtitle':"Integració d'estratègies de reutilització de l'aigua inspirades en la natura amb la presència i l'impacte de microcontaminants i microplàstics mitjançant anàlisi avançada.",
        'project':'Projecte',
        'overview':'Descripció general',
        'packages':'Paquets de treball',
        'field':'Llocs de camp',
        'mesocosm':'Estudis mesocosm',
        'members':'Membres',
        'publis&news':"Publicacions i Notícies",
        'news':'Notícies',
        'conferences':'Conferéncies',
        'publications':'Publicacions',
        'jobOffers':'Ofertes de treball',
        'supporters':'Partidaris',
        'relatedProjects':'Projectes relacionats',
        'advisoryBoard':'Consell assessor',
        'authorities':'Autoritats i utilitats',
        'universities':'Universitats',
        'techCompanies':'Companyies tecnològiques',
        'menu':'MENÚ',
        'h3ProjectOverview':'DESCRIPCIÓ GENERAL',
        'generalInfo':'Informació General',
        'fundingAgency':'AGÈNCIA DE FINANÇAMENT',
        'duration':'DURACIÓ',
        'coordinator':'COORDINADOR',
        'leadResearchers':'INVESTIGADORS PRINCIPALS',
        'otherResearchers':'ALTRES INVESTIGADORS',
        'budget':'PRESUPOST',
        'fundingInfo':"Agència estatal d'investigació Espanyola (AEI), Codi: PID2020-115456RB-I00",
        'linkInfoProjecte':'Informació del projecte',
        'h3WorkPackages':'PAQUETS DE TREBALL',
        'h3FieldSites':'LLOCS DE CAMP',
        'h3Mesocosm':'ESTUDIS MESOCOSM',
        'h3Members':'MEMBRES',
        'h3News':'NOTÍCIES',
        'h3RelatedProjects':'PROJECTES RELACIONATS',
        'h3Advisory':'CONSELL ASSESSOR',
        'h3Authorities':'AUTORITATS I UTILITATS',
        'h3Universities':'UNIVERSITATS',
        'h3techCompanies':'COMPANYIES TECNOLÒGIQUES I ALTRES',
        'h3Conferences':'CONFERÉNCIES',
        'h3Publications':'PUBLICACIONS',
        'h3JobOffers':'OFERTES DE FEINA',
        'about':'Sobre',
        'quickLinks':'Enllaços ràpids',
        'text1span1':"L'objectiu del projecte ReUseMP3 és explorar la viabilitat de l'ús de ",
        'text1span2':"(NBS) amb finalitats de reutilització directa, inclòs el",
        'text1span3':"a les ciutats per a la producció d'aliments de manera més sostenible.",
        'text1span4':"S'aplica una",
        'text1span5':" inclosa l'anàlisi target de",
        'text1span6':"coneguts, però també un wide-scope suspect i non-target per proporcionar una millor visió general de la presència i eliminació de substàncies de preocupació emergent al llarg del cicle de reutilització de laigua, així com el seu",
        'text1span7':"i els additius també es controlen en aquests estudis, que inclouen",
        'text1span8':"en condicions controlades amb aigües residuals/grises reals, així com",
        'text1span9':"Totes les dades recopilades durant el projecte també permetran desenvolupar",
        'text1b1':"solucions basades en la natura ",
        'text1b2':" reg de cultius",
        'text1b3':"varietat de metodologies analítiques,",
        'text1b4':"contaminants emergents",
        'text1b5':"impacte en el medi ambient i la salut humana",
        'text1b6':"Els microplàstics",
        'text1b7':"experiments a escala de laboratori",
        'text1b8':"estudis de camp",
        'text1b9':"eines innovadores de suport a la presa de decisions per a la gestió de l'aigua",
        "wp1":"Sistemes hidropònics de tractament i reutilització d'aigües grises per a la producció de cultius en condicions controlades",
        "wp2":"Estudis de camp de reg amb aigua regenerada per a la producció de cultius i/o aplicacions de NBS",
        "wp3":"Eines analítiques avançades per monitoritzar tecnologies de tractament d'aigua i sistemes de reg",
        "wp4":"Avaluació del risc ambiental (ERA)",
        "wp5":"Avaluació del risc humà derivat de la producció de cultius",
        "wp6":"Eina ReUseMP3 de suport a la presa de decisions",
        "field1":" Jardins municipals regats amb aigües residuals urbanes tractades (tractament terciari)",
        "field2":" Vinyes regades amb aigües residuals urbanes tractades (tractament terciari)",
        "field3":" Plantes ornamentals i comestibles regades amb aigües grises tractades amb NBS (aiguamolls construït hidropònic)",
        "field4":" Hort urbà regat amb aigües grises tractades amb NBS (paret vertical)",
        "field5":" Herbes regades amb aigües residuals urbanes tractades amb NBS (UASB-aiguamolls construït)",
        "lesbos":"Lesbos (Grècia):",
        "mesocosmText":"La planta pilot hidropònica es va construir a la plataforma ICRA PLANTEA per provar el tractament d'aigües grises sintètiques i/o reals i la producció de cultius de plantes comestibles. El sistema està compost per diverses línies que poden treballar en paral·lel, amb entrades d'aigua diferents, i sensors de temperatura, humitat i intensitat lumínica. Els canals es poden emplenar amb argila expandida (LECA) com a substrat inert i poden albergar fins a 8 plantes per canal. La presència d'aeració a l'interior dels canals s'obté introduint dissipadors d'aire a l'aigua, si cal.",
        "aboutText":"L'objectiu del projecte ReUseMP3 és explorar la viabilitat de l'ús de solucions basades en la natura (NBS) amb finalitats de reutilització directa, inclòs el reg de cultius a les ciutats per a la producció d'aliments de manera més sostenible. S'aplica una varietat de metodologies analítiques, inclosa l'anàlisi target de contaminants emergents coneguts, però també un wide-scope suspect i non-target per proporcionar una millor visió general de la presència i eliminació de substàncies de preocupació emergent al llarg del cicle de reutilització de laigua, així com el seu impacte en el medi ambient i la salut humana.",
        "footerFundingText":"Projecte financiat per AEI amb el codi PID2020-115456RB-I00 /MCIN/AEI /10.13039/501100011033.",
        "moreInfo":"Més informació",
        "publiLink":"LINK DE LA PUBLICACIÓ",
    }
}