var arrLang = {
    'en':{
        'subtitle':'Integrating nature-based water Reuse strategies with advanced Monitoring of the Presence and impact of MicroPollutants and MicroPlastics.',
        'project':'Project',
        'overview':'Overview',
        'packages':'Work Packages',
        'field':'Field sites',
        'mesocosm':'Mesocosm studies',
        'members':'Members',
        'publis&news':"Publications & News",
        'news':'News',
        'conferences':'Conferences',
        'publications':'Publications',
        'jobOffers':'Job Offers',
        'supporters':'Supporters',
        'relatedProjects':'Related projects',
        'advisoryBoard':'Advisory board',
        'authorities':'Authorities & utilities',
        'universities':'Universities',
        'techCompanies':'Tech. companies',
        'menu':'MENU',
        'h3ProjectOverview':'PROJECT OVERVIEW',
        'generalInfo':'General Information',
        'fundingAgency':'FUNDING AGENCY',
        'duration':'DURATION',
        'coordinator':'COORDINATOR',
        'leadResearchers':'LEAD RESEARCHERS',
        'otherResearchers':'OTHER RESEARCHERS',
        'budget':'BUDGET',
        'fundingInfo':'Spanish State Research Agency (AEI), Code: PID2020-115456RB-I00',
        'linkInfoProjecte':'Project information',
        'h3WorkPackages':'WORK PACKAGES',
        'h3FieldSites':'FIELD SITES',
        'h3Mesocosm':'MESOCOSM STUDIES',
        'h3Members':'MEMBERS',
        'h3News':'NEWS',
        'h3RelatedProjects':'RELATED PROJECTS',
        'h3Advisory':'ADVISORY BOARD',
        'h3Authorities':'AUTHORITIES & UTILITIES',
        'h3Universities':'UNIVERSITIES',
        'h3techCompanies':'TECH. COMPANIES & OTHERS',
        'h3Conferences':'CONFERENCES',
        'h3Publications':'PUBLICATIONS',
        'h3JobOffers':'JOB OFFERS',
        'about':'About',
        'quickLinks':'Quick Links',
    },
    'es':{
        'subtitle':'',
        'project':'Proyecto',
        'overview':'Descripción general',
        'packages':'Paquetes de trabajo',
        'field':'Sitios de campo',
        'mesocosm':'Estudios mesocosm',
        'members':'Miembros',
        'publis&news':"Publicaciones y Noticias",
        'news':'Noticias',
        'conferences':'Conferencias',
        'publications':'Publicaciones',
        'jobOffers':'Ofertas de trabajo',
        'supporters':'Partidarios',
        'relatedProjects':'Proyectos relacionados',
        'advisoryBoard':'Junta asesora',
        'authorities':'Autoridades y utilidades',
        'universities':'Universidades',
        'techCompanies':'Empresas tecnológicas',
        'menu':'MENÚ',
        'h3ProjectOverview':'DESCRIPCIÓN GENERAL',
        'generalInfo':'Información General',
        'fundingAgency':'AGENCIA DE FINANCIAMIENTO',
        'duration':'DURACIÓN',
        'coordinator':'COORDINADOR',
        'leadResearchers':'INVESTIGADORES PRINCIPALES',
        'otherResearchers':'OTROS INVESTIGADORES',
        'budget':'PRESUPUESTO',
        'fundingInfo':'Agencia estatal de investigación Española (AEI), Codigo: PID2020-115456RB-I00',
        'linkInfoProjecte':'Información del proyecto',
        'h3WorkPackages':'PAQUETES DE TRABAJO',
        'h3FieldSites':'SITIOS DE CAMPO',
        'h3Mesocosm':'ESTUDIOS MESOCOSM',
        'h3Members':'MIEMBROS',
        'h3News':'NOTICIAS',
        'h3RelatedProjects':'PROYECTOS RELACIONADOS',
        'h3Advisory':'JUNTA ASESORA',
        'h3Authorities':'AUTORIDADES Y UTILIDADES',
        'h3Universities':'UNIVERSIDADES',
        'h3techCompanies':'EMPRESAS TECNOLÓGICAS Y OTROS',
        'h3Conferences':'CONFERENCIAS',
        'h3Publications':'PUBLICACIONES',
        'h3JobOffers':'OFERTAS DE TRABAJO',
        'about':'Acerca de',
        'quickLinks':'Enlaces rápidos',
    },
    'cat':{
        'subtitle':'',
        'project':'Projecte',
        'overview':'Descripció general',
        'packages':'Paquets de treball',
        'field':'Llocs de camp',
        'mesocosm':'Estudis mesocosm',
        'members':'Membres',
        'publis&news':"Publicacions i Notícies",
        'news':'Notícies',
        'conferences':'Conferéncies',
        'publications':'Publicacions',
        'jobOffers':'Ofertes de treball',
        'supporters':'Partidaris',
        'relatedProjects':'Projectes relacionats',
        'advisoryBoard':'Consell assessor',
        'authorities':'Autoritats i utilitats',
        'universities':'Universitats',
        'techCompanies':'Companyies tecnològiques',
        'menu':'MENÚ',
        'h3ProjectOverview':'DESCRIPCIÓ GENERAL',
        'generalInfo':'Informació General',
        'fundingAgency':'AGÈNCIA DE FINANÇAMENT',
        'duration':'DURACIÓ',
        'coordinator':'COORDINADOR',
        'leadResearchers':'INVESTIGADORS PRINCIPALS',
        'otherResearchers':'ALTRES INVESTIGADORS',
        'budget':'PRESUPOST',
        'fundingInfo':"Agència estatal d'investigació Espanyola (AEI), Codi: PID2020-115456RB-I00",
        'linkInfoProjecte':'Informació del projecte',
        'h3WorkPackages':'PAQUETS DE TREBALL',
        'h3FieldSites':'LLOCS DE CAMP',
        'h3Mesocosm':'ESTUDIS MESOCOSM',
        'h3Members':'MEMBRES',
        'h3News':'NOTÍCIES',
        'h3RelatedProjects':'PROJECTES RELACIONATS',
        'h3Advisory':'CONSELL ASSESSOR',
        'h3Authorities':'AUTORITATS I UTILITATS',
        'h3Universities':'UNIVERSITATS',
        'h3techCompanies':'COMPANYIES TECNOLÒGIQUES I ALTRES',
        'h3Conferences':'CONFERÉNCIES',
        'h3Publications':'PUBLICACIONS',
        'h3JobOffers':'OFERTES DE FEINA',
        'about':'Sobre',
        'quickLinks':'Enllaços ràpids',
    }
}